export const GET_WINES = "GET_WINES";
export const GET_WINES_BY_PRICE = "GET_WINES_BY_PRICE";
export const GET_WINES_BY_VINTAGE = "GET_WINES_BY_VINTAGE";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";